// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://hjiublwdlvzmowxldstd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaXVibHdkbHZ6bW93eGxkc3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDMwNDgsImV4cCI6MjA2NjU3OTA0OH0.AH2wU43zcGTwr5s3p8v1r2rwg1bIMREFhe7Qn4g21RY';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
